version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - nodenet

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: zaphodbrox/api:latest
    container_name: api

    networks:
      - nodenet
    volumes:
      - ./api:/usr/src/app
    tty: true
    ports:
      - 3003:3003
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: zaphodbrox/nginx:latest
    container_name: nginx
    networks:
      - nodenet
    ports:
      - 8080:80

networks:
  nodenet:
    driver: bridge
